export enum BlockType {
    Program = 'Program',
    Generic = 'Generic',
    Func = 'Func',
    If = 'If',
    ElseIf = 'ElseIf',
    Else = 'Else',
    While = 'While',
    Do = 'Do',
    For = 'For',
    Switch = 'Switch',
    SwitchCase = 'SwitchCase',
    Select = 'Select',
    SelectCase = 'SelectCase',
    With = 'With',
}