export enum TokenType {
    EOF = 'EOF',
    EOL = 'EOL',
    Directive = 'Directive',
    Keyword = 'Keyword',
    Identifier = 'Identifier',
    Variable = 'Variable',
    Macro = 'Macro',
    Number = 'Number',
    String = 'String',
    Bracket = 'Bracket',
    // LParen = 'LParen',
    // RParen = 'RParen',
    // LSquare = 'LSquare',
    // RSquare = 'RSquare',
    Comma = 'Comma',
    Dot = 'Dot',
    Operator = 'Operator',
}