export enum TokenType {
    EOF = 'EOF',
    EOL = 'EOL',
    Directive = 'Directive',
    Keyword = 'Keyword',
    Identifier = 'Identifier',
    Variable = 'Variable',
    Macro = 'Macro',
    Number = 'Number',
    String = 'String',
    LParen = 'LParen',
    RParen = 'RParen',
    LSquare = 'LSquare',
    RSquare = 'RSquare',
    Comma = 'Comma',
    Dot = 'Dot',
    Operator = 'Operator',
}