function unavailable(name: string): Error {
    return new Error(`@${name} is not available`);
}


export const macros = {
    _var: {
        error: 0,
        extended: 0,
        exitCode: 0,
    },
    get APPDATACOMMONDIR() { throw unavailable('AppDataCommonDir'); },
    get APPDATADIR() { throw unavailable('AppDataDir'); },
    AUTOITVERSION: '3.3.16.1',
    AUTOITX64: 1,
    get COMMONFILESDIR() { throw unavailable('CommonFilesDir'); },
    COMPILED: 0,
    COMPUTERNAME: 'Computer',
    CR: '\r',
    CRLF: '\r\n',
    get DESKTOPCOMMONDIR() { throw unavailable('DesktopCommonDir'); },
    DESKTOPDEPTH: 32,
    get DESKTOPDIR() { throw unavailable('DesktopDir'); },
    get DESKTOPHEIGHT() { return window.innerHeight; },
    DESKTOPREFRESH: 60,
    get DESKTOPWIDTH() { return window.innerWidth; },
    get ERROR() { return this._var.error; },
    get EXTENDED() { return this._var.extended; },
    get EXITCODE() { return this._var.exitCode; },
    get HOUR() { return new Date().getHours(); },
    LF: '\n',
    get MDAY() { return new Date().getDate(); },
    get MIN() { return new Date().getMinutes(); },
    get MON() { return new Date().getMonth() + 1; },
    get MSEC() { return new Date().getMilliseconds(); },
    get OSLANG() { return '0409'; },
    get SCRIPTDIR() { throw unavailable('ScriptDir'); },
    get SCRIPTFULLPATH() { throw unavailable('ScriptFullPath'); },
    SCRIPTLINENUMBER: 0,
    get SCRIPTNAME() { throw unavailable('ScriptName'); },
    get SEC() { return new Date().getSeconds(); },
    get STARTMENUCOMMONDIR() { throw unavailable('StartMenuCommonDir'); },
    get STARTMENUDIR() { throw unavailable('StartMenuDir'); },
    get STARTUPCOMMONDIR() { throw unavailable('StartupCommonDir'); },
    get STARTUPDIR() { throw unavailable('StartupDir'); },
    SW_HIDE: 0,
    SW_MAXIMIZE: 3,
    SW_MINIMIZE: 6,
    SW_RESTORE: 9,
    SW_SHOW: 5,
    SW_SHOWDEFAULT: 10,
    SW_SHOWMAXIMIZED: 3,
    SW_SHOWMINIMIZED: 2,
    SW_SHOWMINNOACTIVE: 7,
    SW_SHOWNA: 8,
    SW_SHOWNOACTIVATE: 4,
    SW_SHOWNORMAL: 1,
    get SYSTEMDIR() { throw unavailable('SystemDir'); },
    TAB: '\t',
    get TEMPDIR() { throw unavailable('TempDir'); },
    USERNAME: 'User',
    get USERPROFILEDIR() { throw unavailable('UserProfileDir'); },
    get WDAY() { return new Date().getDay() + 1; },
    get WINDOWSDIR() { throw unavailable('WindowsDir'); },
    get WORKINGDIR() { throw unavailable('WorkingDir'); },
    get YDAY() {
        const d = new Date();
        return (d.getTime() - d.setMonth(0, 1)) / (24 * 3600 * 1000) + 1;
    },
    get YEAR() { return new Date().getFullYear(); },
};